
Bienvenid@ al repositorio de retos propuestos por la Universidad Nacional de Colombia, 
en el marco del Ciclo 1 del programa del Gobierno Misión Mintic 2022.

Las soluciones a los retos son de mi autoría, sin embargo, son de libre
uso. Si deseas contribuir con tu solución a cualquiera de los retos aquí descritos,
recuerda que puedes añadir un comentario al inicio del archivo con tu nombre y enlace de GitHub.
Por ejemplo:

#+BEGIN_SRC python
  # Author: [Jonathan Meza](https://github.com/JonathanMeza0107)
#+END_SRC

** Listado de Retos por Ciclo
*** Ciclo 1 - Python
En el ciclo 1 se impartieron los fundamentos de la programación
utilizando Python, iniciando con los tipos de datos, funciones,
estructuras condicionales, estructuras de datos y librerías. 

Los retos fueron diseñados de tal manera que se pudieran realizar con los conocimientos 
aprendidos durante el transcurso del ciclo.

- [[file:./Reto_1/][Reto 1]]
- [[file:./Reto_2][Reto 2]]
- [[file:./Reto_3][Reto 3]]
- [[file:./Reto_4][Reto 4]]

