Bienvenid@ al repositorio de retos propuestos por la Universidad Nacional de Colombia, 
en el marco del Ciclo 1 del programa de formación de Programación de Software, 
Misión Tic 2022.

** Ciclo 1 - Python
En el ciclo 1 se impartieron los fundamentos de la programación 
de software utilizando Python, iniciando con los tipos de datos, 
funciones, estructuras condicionales, estructuras de datos y librerías. 

Los retos fueron diseñados de tal manera que se pudieran realizar con los conocimientos 
aprendidos durante el transcurso del ciclo.

*** Listado de Retos:

- [[file:./Retos/Reto_1/][Reto 1]]
- [[file:./Retos/Reto_2][Reto 2]]
- [[file:./Retos/Reto_3][Reto 3]]
- [[file:./Retos/Reto_4][Reto 4]]
- [[file:./Retos/Reto_5][Reto 5]]


** ¿Qué es Python?

[[https://en.wikipedia.org/wiki/Guido_van_Rossum]]

Python es un lenguaje de programación creado por [[https://en.wikipedia.org/wiki/Guido_van_Rossum][Guido Van Rossum]], con una sintaxis muy limpia, ideado para enseñar a la gente a programar bien. Se trata de un lenguaje interpretado o de script.
